# -*- coding: utf-8 -*-
# method_list_by_Jink.py

method_list_by_Jink = [
	'action research',
	'analysis of variance',
	'analytic induction',
	'anti-racism research',
	'applied research',
	'area sampling',
	'atlas.ti',
	'auditing',
	'autoethnography',
	'caqdas',
	'case study method',
	'CASIC (Computer assisted survey information collection)',
	'causal model',
	'census',
	'chi-square test',
	'cluster analysis',
	'coding',
	'community study method',
	'comparative method',
	'composite measurement',
	'constant comparative method',
	'constructionism',
	'content analysis',
	'conversation analysis',
	'cost-benefit analysis',
	'covert research',
	'critical ethnography',
	'critical research',
	'cross-sectional survey',
	'cultural research',
	'dangerous fieldwork',
	'data archives',
	'decision making research',
	'descriptive statistics',
	'deviant case analysis',
	'diary',
	'dissability research',
	'disaster research',
	'disastrous research',
	'discourse analysis',
	'discriminant function analysis',
	'document analysis',
	'ecological fallacy',
	'econometrics',
	'elite interviewing',
	'elite selection',
	'emancipatory research',
	'empiricism',
	'epistemology',
	'error',
	'ethics',
	'the ethnograph 5.0',
	'ethnographic interviewing',
	'ethnography',
	'ethnomethodology',
	'evaluation research',
	'experiment',
	'exploitative research',
	'exploratory research',
	'extending social research',
	'factor analysis',
	'falsification',
	'feminist research',
	'field experiment',
	'fieldwork',
	'focus group',
	'forecasting',
	'garbology',
	'gatekeeper',
	'general linear modelling',
	'GIS',
	'good practice studies',
	'grounded theory',
	'hermeneutics',
	'historical analysis',
	'hunting (snooping and fishing)',
	'hypothesis',
	'hypthetico-deductive model',
	'idealtype',
	'idiographic',
	'impression management',
	'indicator',
	'induction',
	'inferrential statistics',
	'informed consent',
	'intellectual craftsmanship',
	'internet research',
	'interpretative repertoires',
	'inter-subjective understanding',
	'interview',
	'life history interviewing',
	'likert scale',
	'literature review',
	'log-linear analysis',
	'logitudinal study',
	'marketing research',
	'measurement',
	'media analysis',
	'messy research (complex evaluation)',
	'meta-analysis',
	'methodological pluralism',
	'methodology',
	'microethnography',
	'mixed methods research',
	'mocelling',
	'multiple indicators',
	'multivariate analysis',
	'narrative analysis',
	'narrative interviewing',
	'naturalistic data',
	'netnography',
	'network analysis',
	'non-probability (non-random) sampling',
	'official statistics',
	'one-shot design',
	'ontology',
	'operationalization',
	'opportunity sampling',
	'oral history',
	'organizational research',
	'panel study',
	'paradigm',
	'parametric tests',
	'participant observatio',
	'participatory action research',
	'path analysis',
	'performance indicator',
	'phenomenology',
	'photography',
	'policy-related research',
	'politics and social research',
	'positioning theory',
	'positivism',
	'postmodernism',
	'practitioner research',
	'prediction',
	'primary research',
	'probability (random) sampling',
	'process mapping',
	'progressive focusing',
	'projective technique',
	'prospective study',
	'purposive study',
	'purposive sampling',
	'QSR NVIVO',
	'qualitative data archives (ESDS IASSIS ICPSR ICPSR)',
	'qualitative research',
	'quantitative research',
	'quasi-experiment',
	'questionnaire',
	'quota sampling',
	'random sampling',
	'reactivity or validity of measurement',
	'realism',
	'reflexivity',
	'regression analysis',
	'relativism',
	'reliability',
	'repertory grid technique',
	'research bargain',
	'research problems',
	'retrospective study',
	'sampling',
	'scaling',
	'secondary analysis',
	'self-report study',
	'semantic differential scale',
	'semiotics or textual analysis',
	'sensitive research',
	'sensitizing concepts',
	'simulation',
	'snowball sampling',
	'social indicators',
	'social survey',
	'sociometry',
	'spatial research',
	'SPSS',
	'standpoint research',
	'statistical significance or inferential statistics',
	'stratified sampling',
	'structured observation',
	'subjectivity',
	'summated rating scale',
	'textual analysis',
	'theoretical sampling',
	'thick description',
	'thurstone scale',
	'time series design',
	'trace measures',
	'transcription',
	'triagulation',
	'type 1 and type 2 errors',
	'unobtrusive measurement',
	'validity',
	'validity of explanation',
	'validity of generalization',
	'validity of measurement',
	'value free research',
	'variable analysis',
	'videography',
	'visual methods',
	'volunteer sampling',
	'writing research',
	'access',
	'bias']

from_some_book = [
	'action research',
	'analysis of variance',
	'analytic induction',
	'anti-racism research',
	'applied research',
	'area sampling',
	'atlas.ti',
	'auditing',
	'autoethnography',
	'caqdas',
	'case study method',
	'CASIC (Computer assisted survey information collection)',
	'causal model',
	'census',
	'chi-square test',
	'cluster analysis',
	'coding',
	'community study method',
	'comparative method',
	'composite measurement',
	'constant comparative method',
	'constructionism',
	'content analysis',
	'conversation analysis',
	'cost-benefit analysis',
	'covert research',
	'critical ethnography',
	'critical research',
	'cross-sectional survey',
	'cultural research',
	'dangerous fieldwork',
	'data archives',
	'decision making research',
	'descriptive statistics',
	'deviant case analysis',
	'diary',
	'dissability research',
	'disaster research',
	'disastrous research',
	'discourse analysis',
	'discriminant function analysis',
	'document analysis',
	'ecological fallacy',
	'econometrics',
	'elite interviewing',
	'elite selection',
	'emancipatory research',
	'empiricism',
	'epistemology',
	'error',
	'ethics',
	'the ethnograph 5.0',
	'ethnographic interviewing',
	'ethnography',
	'ethnomethodology',
	'evaluation research',
	'experiment',
	'exploitative research',
	'exploratory research',
	'extending social research',
	'factor analysis',
	'falsification',
	'feminist research',
	'field experiment',
	'fieldwork',
	'focus group',
	'forecasting',
	'garbology',
	'gatekeeper',
	'general linear modelling',
	'GIS',
	'good practice studies',
	'grounded theory',
	'hermeneutics',
	'historical analysis',
	'hunting (snooping and fishing)',
	'hypothesis',
	'hypthetico-deductive model',
	'idealtype',
	'idiographic',
	'impression management',
	'indicator',
	'induction',
	'inferrential statistics',
	'informed consent',
	'intellectual craftsmanship',
	'internet research',
	'interpretative repertoires',
	'inter-subjective understanding',
	'interview',
	'life history interviewing',
	'likert scale',
	'literature review',
	'log-linear analysis',
	'logitudinal study',
	'marketing research',
	'measurement',
	'media analysis',
	'messy research (complex evaluation)',
	'meta-analysis',
	'methodological pluralism',
	'methodology',
	'microethnography',
	'mixed methods research',
	'mocelling',
	'multiple indicators',
	'multivariate analysis',
	'narrative analysis',
	'narrative interviewing',
	'naturalistic data',
	'netnography',
	'network analysis',
	'non-probability (non-random) sampling',
	'official statistics',
	'one-shot design',
	'ontology',
	'operationalization',
	'opportunity sampling',
	'oral history',
	'organizational research',
	'panel study',
	'paradigm',
	'parametric tests',
	'participant observatio',
	'participatory action research',
	'path analysis',
	'performance indicator',
	'phenomenology',
	'photography',
	'policy-related research',
	'politics and social research',
	'positioning theory',
	'positivism',
	'postmodernism',
	'practitioner research',
	'prediction',
	'primary research',
	'probability (random) sampling',
	'process mapping',
	'progressive focusing',
	'projective technique',
	'prospective study',
	'purposive study',
	'purposive sampling',
	'QSR NVIVO',
	'qualitative data archives (ESDS IASSIS ICPSR ICPSR)',
	'qualitative research',
	'quantitative research',
	'quasi-experiment',
	'questionnaire',
	'quota sampling',
	'random sampling',
	'reactivity or validity of measurement',
	'realism',
	'reflexivity',
	'regression analysis',
	'relativism',
	'reliability',
	'repertory grid technique',
	'research bargain',
	'research problems',
	'retrospective study',
	'sampling',
	'scaling',
	'secondary analysis',
	'self-report study',
	'semantic differential scale',
	'semiotics or textual analysis',
	'sensitive research',
	'sensitizing concepts',
	'simulation',
	'snowball sampling',
	'social indicators',
	'social survey',
	'sociometry',
	'spatial research',
	'SPSS',
	'standpoint research',
	'statistical significance or inferential statistics',
	'stratified sampling',
	'structured observation',
	'subjectivity',
	'summated rating scale',
	'textual analysis',
	'theoretical sampling',
	'thick description',
	'thurstone scale',
	'time series design',
	'trace measures',
	'transcription',
	'triagulation',
	'type 1 and type 2 errors',
	'unobtrusive measurement',
	'validity',
	'validity of explanation',
	'validity of generalization',
	'validity of measurement',
	'value free research',
	'variable analysis',
	'videography',
	'visual methods',
	'volunteer sampling',
	'writing research',
	'access',
	'bias']


"""
	'http://ecite.utas.edu.au/rmdb/ecite/q/ecite_view_subject_for'
"""

subjects = [
	'01', 'Mathematical Sciences (556)',
	'02', 'Physical Sciences (1,283)',
	'03', 'Chemical Sciences (2,142)',
	'04', 'Earth Sciences (3,406)',
	'05', 'Environmental Sciences (2,883)',
	'06', 'Biological Sciences (6,708)',
	'07', 'Agricultural and Veterinary Sciences (7,125)',
	'08', 'Information and Computing Sciences (1,773)',
	'09', 'Engineering (2,591)',
	'10', 'Technology (202)',
	'11', 'Medical and Health Sciences (10,325)',
	'12', 'Built Environment and Design (1,000)',
	'13', 'Education (3,621)',
	'14', 'Economics (948)',
	'15', 'Commerce, Management, Tourism and Services (1,757)',
	'16', 'Studies in Human Society (4,935)',
	'17', 'Psychology and Cognitive Sciences (1,787)',
	'18', 'Law and Legal Studies (2,385)',
	'19', 'Studies in Creative Arts and Writing (4,282)',
	'20', 'Language, Communication and Culture (1,983)',
	'21', 'History and Archaeology (2,180)',
	'22', 'Philosophy and Religious Studies (993)']



url= 'http://ecite.utas.edu.au/rmdb/ecite/q/ecite_view_subject_for/01'
url= 'http://ecite.utas.edu.au/rmdb/ecite/q/ecite_view_subject_for/{}'.format(num)
url= 'http://ecite.utas.edu.au/rmdb/ecite/q/ecite_view_subject_for/{}{}'.format(num, subnum)
url = 'http://ecite.utas.edu.au/rmdb/ecite/q/ecite_view_subject_for/{}{}{}'.format(number, subnum, subsubnum)

'''
'li', 'style':"font-size:10pt"
'''
