"""
Table 6. Cross-citation clusters for 221 ISI science and social sciences categories 
Cluster # ISI subject categories

"""
columns = [
    {'computer science, informatics': [
		'Automation & Control Systems',
		'Computer Science, Artificial Intelligence',
		'Computer Science, Cybernetics',
		'Computer Science, Hardware & Architecture',
		'Computer Science, Information Systems',
		'Computer Science, Interdisciplinary Applications',
		'Computer Science, Software Engineering',
		'Computer Science, Theory & Methods',
		'Engineering, Electrical & Electronic',
		'Engineering, Industrial',
		'Engineering, Manufacturing',
		'Ergonomics',
		'Information Science & Library Science',
		'Mathematical & Computational Biology',
		'Mathematics',
		'Mathematics, Applied',
		'Medical Informatics',
		'Operations Research & Management Science',
		'Robotics',
		'Statistics & Probability',
		'Telecommunications',
		'Transportation',
		'Transportation Science & Technology']},
    {'chemistry, physics, engineering':
		['Acoustics',
		'Astronomy & Astrophysics',
		'Biochemical Research Methods',
		'Chemistry, Analytical',
		'Chemistry, Inorganic & Nuclear',
		'Chemistry, Medicinal',
		'Chemistry, Multidisciplinary',
		'Chemistry, Organic',
		'Chemistry, Physical',
		'Crystallography',
		'Electrochemistry',
		'Energy & Fuels',
		'Engineering, Aerospace',
		'Engineering, Chemical',
		'Engineering, Mechanical',
		'Engineering, Multidisciplinary',
		'Instruments & Instrumentation',
		'Materials Science, Ceramics',
		'Materials Science, Characterization, Testing',
		'Materials Science, Coatings & Films',
		'Materials Science, Composites',
		'Materials Science, Multidisciplinary',
		'Mathematics, Interdisciplinary Applications',
		'Mechanics',
		'Metallurgy & Metallurgical Engineering',
		'Mining & Mineral Processing',
		'Nanoscience & Nanotechnology',
		'Nuclear Science & Technology',
		'Optics',
		'Physics, Applied',
		'Physics, Atomic, Molecular & Chemical',
		'Physics, Condensed Matter',
		'Physics, Fluids & Plasmas',
		'Physics, Mathematical',
		'Physics, Multidisciplinary',
		'Physics, Nuclear',
		'Physics, Particles & Fields',
		'Polymer Science',
		'Spectroscopy',
		'Thermodynamics']},
    {'biology, Environmental science, geography': [
		'Agricultural Engineering',
		'Agriculture, Soil Science',
		'Biodiversity Conservation',
		'Biology',
		'Biology, Miscellaneous',
		'Construction & Building Technology',
		'Ecology',
		'Engineering, Civil',
		'Engineering, Environmental',
		'Engineering, Geological',
		'Engineering, Marine',
		'Engineering, Ocean',
		'Engineering, Petroleum',
		'Entomology',
		'Environmental Sciences',
		'Evolutionary Biology',
		'Fisheries',
		'Forestry',
		'Geochemistry & Geophysics',
		'Geography, Physical',
		'Geology',
		'Geosciences, Multidisciplinary',
		'Imaging Science & Photographic Technology',
		'Limnology',
		'Marine & Freshwater Biology',
		'Materials Science, Paper & Wood',
		'Materials Science, Textiles',
		'Meteorology & Atmospheric Sciences',
		'Mineralogy',
		'Oceanography',
		'Ornithology',
		'Paleontology',
		'Remote Sensing',
		'Toxicology',
		'Water Resources',
		'Zoology']},
    {'Agriculture, food science': [
		'Agriculture, Dairy & Animal Science',
		'Agriculture, Multidisciplinary ',
		'Agronomy ',
		'Biotechnology & Applied Microbiology',
		'Chemistry, Applied',
		'Food Science & Technology',
		'Horticulture',
		'Infectious Diseases',
		'Microbiology',
		'Mycology',
		'Nutrition & Dietetics',
		'Parasitiology',
		'Plant Sciences',
		'Tropical Medicine',
		'Veterinary Sciences',
		'Virology']},
    {'life science, medical science': [
		'Allergy',
		'Anatomy & Morphology',
		'Andrology',
		'Anesthesiology',
		'Biochemistry & Molecular Biology',
		'Biophysics',
		'Cardiac & Cardiovascular System',
		'Cell Biology',
		'Critical Care Medicine',
		'Dentistry, Oral Surgery & Medicine',
		'Dermatology & Venereal Diseases',
		'Developmental Biology',
		'Emergency Medicine',
		'Endocrinology & Metabolism',
		'Engineering, Biomedical',
		'Gastroenterology & Hepatology',
		'Genetics & Heredity',
		'Hematology',
		'Immunology',
		'Integrative & Complementary Medicine',
		'Materials Science, Biomaterials',
		'Medical Laboratory Technology',
		'Medicine, General & Internal',
		'Medicine, Research & Experimental',
		'Microscopy',
		'Obstetrics & Gynecology',
		'Oncology',
		'Ophthalmology',
		'Orthopedics',
		'Otorhinolaryngology',
		'Pathology',
		'Pediatrics',
		'Peripheral Vascular Disease',
		'Pharmacology & Pharmacy',
		'Physiology',
		'Radiology, Nuclear Medicine & Medical Imaging',
		'Reproductive Biology',
		'Respiratory System',
		'Rheumatology',
		'Sport Sciences',
		'Surgery',
		'Transplantation',
		'Urology & Nephrol']},
    {'sociology, economics, political science': [
		'Agricultural Economics & Policy',
		'Anthropology',
		'Area Studies',
		'Business',
		'Business, Finance',
		'Communication',
		'Criminology & Penology',
		'Demography',
		'Economics',
		'Education, Scientific Disciplines',
		'Environmental Studies',
		'Ethics',
		'Ethnic Studies',
		'Family Studies',
		'Geography',
		'Health Care Sciences & Services',
		'Health Policy & Services',
		'History',
		'History & Philosophy of Science',
		'History of Social Sciences',
		'Industrial Relations & Labor',
		'International Relations',
		'Law',
		'Management',
		'Medical Ethics',
		'Medicine, Legal',
		'Medieval & Renaissance Studies',
		'Nursing',
		'Planning & Development',
		'Political Science',
		'Psychology, Applied',
		'Public Administration',
		'Public, Environmental & Occupational Health',
		'Social Issues',
		'Social Sciences, Biomedical',
		'Social Sciences, Interdisciplinary',
		'Social Sciences, Mathematical Methods',
		'Social Work',
		'Sociology',
		'Urban Studies',
        "Women's Studies"]},
    {'psychology, education': [
		'Applied Linguistics',
		'Behavioral Sciences',
		'Clinical Neurology',
		'Education & Educational Research',
		'Education, Special',
		'Geriatrics & Gerontology',
		'Gerontology',
		'Neuroimaging',
		'Neurosciences',
		'Psychiatry',
		'Psychology',
		'Psychology, Biological',
		'Psychology, Clinical',
		'Psychology, Developmental',
		'Psychology, Educational',
		'Psychology, Experimental',
		'Psychology, Mathematical',
		'Psychology, Multidisciplinary',
		'Psychology, Psychoanalysis',
		'Psychology, Social',
		'Rehabilitation',
		'Substance Abuse']}]
